연습
------------------0311------------------------------

SELECT *
  FROM EMP;

SELECT EMPNO, ENAME
  FROM EMP;
  
------------------0311-----------------------------

----------------0312-------------------------
SELECT *
  FROM PROD;
  
SELECT PROD_ID, PROD_NAME
  FROM PROD;
  
SELECT *
FROM LPROD;

SELECT BUYER_ID, BUYER_NAME
  FROM BUYER;
  
SELECT *
  FROM CART;
  
SELECT MEM_ID,MEM_PASS,MEM_NAME
  FROM MEMBER;
  
SELECT LPROD_GU AS gu, LPROD_NM AS nm
  FROM LPROD;
  
SELECT BUYER_ID AS 바이어아이디, BUYER_NAME AS 이름
  FROM BUYER;
  
SELECT 'SELECT ' || '*' || 'FROM ' || TABLE_NAME || ';'
  FROM USER_TABLES;

SELECT 'SELECT * FROM ' || TABLE_NAME ||';',
        CONCAT('SELECT * FROM', TABLE_NAME)
  FROM USER_TABLES;
  
SELECT CONCAT(CONCAT('SELECT * FROM', TABLE_NAME), ';')
  FROM USER_TABLES;
  
SELECT CONCAT('SELECT * FROM', TABLE_NAME) || ';'
  FROM USER_TABLES;
  
SELECT 'SELECT * FROM ' || CONCAT(TABLE_NAME, ';'),
        CONCAT('SELECT * FROM ' || TABLE_NAME, ';')
  FROM USER_TABLES;
  
SELECT *
  FROM EMP
 WHERE DEPTNO = 10;
 
SELECT *
  FROM USERS
 WHERE USERID = 'brown';
 
SELECT *
  FROM EMP
 WHERE DEPTNO > 20;
 
SELECT *
  FROM EMP
 WHERE DEPTNO != 20;

SELECT *
  FROM EMP
 WHERE 1=1;
 
SELECT *
  FROM EMP
 WHERE 1=2;

-----------------------------------0312---------------

--------------------------------0315-----------------------------
 
SELECT EMPNO, ENAME, HIREDATE
  FROM EMP
 WHERE HIREDATE >= TO_DATE('1981/03/01', 'YYYY/MM/DD');
 
SELECT *
  FROM EMP
 WHERE HIREDATE >= TO_DATE('1982/01/01', 'YYYY/MM/DD');
 
SELECT ENAME, HIREDATE
  FROM EMP
 WHERE HIREDATE BETWEEN TO_DATE('1982/01/01', 'YYYY/MM/DD') AND TO_DATE('1983/01/01', 'YYYY/MM//DD');
 
SELECT ENAME, HIREDATE
  FROM EMP
 WHERE HIREDATE >= TO_DATE('1982/01/01', 'YYYY/MM/DD')
   AND HIREDATE <= TO_DATE('1983/01/01', 'YYYY/MM/DD');
   
SELECT USERID AS 아이디, USERNM AS 이름, ALIAS AS 별명
  FROM USERS
 WHERE USERID IN('brown', 'cony', 'sally');
 
SELECT USERID AS 아이디, USERNM AS 이름, ALIAS AS 별명
  FROM USERS
 WHERE USERID = 'brown'
    OR USERID = 'cony' 
    OR USERID = 'sally';
    
SELECT *
  FROM USERS
 WHERE USERID LIKE 'c%';
 
SELECT *
  FROM USERS
 WHERE USERID LIKE 'c___';
 
SELECT *
  FROM USERS
 WHERE USERID LIKE '%1%';
 
SELECT MEM_ID, MEM_NAME
  FROM MEMBER
 WHERE MEM_NAME LIKE '신%';
 
SELECT MEM_ID, MEM_NAME
  FROM MEMBER
 WHERE MEM_NAME LIKE '%이%';
 
SELECT *
  FROM EMP
 WHERE MGR IS NULL;
 
SELECT *
  FROM EMP
 WHERE MGR = 7698 AND SAL > 1000;
 
SELECT *
  FROM EMP
WHERE MGR = 7698 OR SAL > 1000;

SELECT *
  FROM EMP
 WHERE DEPTNO NOT IN (30);
 
SELECT *
  FROM EMP
 WHERE DEPTNO != 30;
 
SELECT *
  FROM EMP
 WHERE JOB = 'SALESMAN' AND HIREDATE >= TO_DATE('1981/06/01', 'YYYY/MM/DD');
 
SELECT *
  FROM EMP
 WHERE DEPTNO != 10 AND HIREDATE >= TO_DATE('1981/06/01', 'YYYY/MM/DD');
 
SELECT *
  FROM EMP
 WHERE DEPTNO IN (20,30) AND HIREDATE >= TO_DATE('1981/06/01', 'YYYY/MM/DD');
 
SELECT *
  FROM EMP
 WHERE JOB = 'SALESMAN' OR HIREDATE >= TO_DATE('1981/06/01', 'YYYY/MM/DD');
 
SELECT *
  FROM EMP
 WHERE JOB = 'SALESMAN' OR EMPNO LIKE ('78%');
 
SELECT *
  FROM EMP
 WHERE JOB = 'SALSEMAN' OR EMPNO BETWEEN 7800 AND 7899
                        OR EMPNO BETWEEN 780 AND 789
                        OR EMPNO = 78;
---------------------------0315---------------------------

-----------------------0316----------------------------

SELECT *
  FROM EMP
 WHERE JOB = 'SALESMAN' OR EMPNO LIKE '78%' AND HIREDATE >= TO_DATE('1981/06/01', 'YYYY/MM/DD');
 
SELECT *
  FROM DEPT
 ORDER BY DNAME;
 
SELECT *
FROM DEPT
 ORDER BY LOC DESC;
 
SELECT *
  FROM EMP
 WHERE COMM IS NOT NULL
   AND COMM !=0
 ORDER BY COMM DESC, EMPNO DESC;
 
SELECT *
  FROM EMP
 WHERE MGR IS NOT NULL
 ORDER BY JOB, EMPNO DESC;
 
SELECT *
  FROM EMP
 WHERE DEPTNO IN (10,30) AND SAL > 1500
 ORDER BY ENAME DESC;